"""autogenerated by genmsg_py from DriveBase.msg. Do not edit."""
import roslib.message
import struct


class DriveBase(roslib.message.Message):
  _md5sum = "65986bed022cdc1fac2edc1016acb2c6"
  _type = "alfred_msg/DriveBase"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# A message which indicates an output to send to the motors
# each motor value is a percentage, wher 0% is full reverse,
# 100% is full forward, and 50% is no power

float32 motor1
float32 motor2
float32 motor3


"""
  __slots__ = ['motor1','motor2','motor3']
  _slot_types = ['float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       motor1,motor2,motor3
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(DriveBase, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motor1 is None:
        self.motor1 = 0.
      if self.motor2 is None:
        self.motor2 = 0.
      if self.motor3 is None:
        self.motor3 = 0.
    else:
      self.motor1 = 0.
      self.motor2 = 0.
      self.motor3 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3f.pack(_x.motor1, _x.motor2, _x.motor3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.motor1, _x.motor2, _x.motor3,) = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3f.pack(_x.motor1, _x.motor2, _x.motor3))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.motor1, _x.motor2, _x.motor3,) = _struct_3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_3f = struct.Struct("<3f")
